// src/views/downloads/Downloads.svelte
<h1>Downloads</h1>

<hr>
<br />

<div class="downloads__versions">
  {#each versions as version, index}
    <VersionCard version={version} latest={index === 0} />
  {/each}
</div>

<script>
  import VersionCard from '../../components/VersionCard.svelte'
  import versions from './versions'

</script>

<style>
  .downloads__versions {
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }
</style>

// src/pages/old/downloads/index.vue
<template>
  <v-row>
    <v-col cols="12">
      <h1>Downloads</h1>
      <hr />
      <br />
      <v-row>
        <v-col
          v-for="(version, index) in versions"
          :key="index"
          cols="12"
        >
          <DownloadCard
            :version="version"
            :latest="index === 0"
          >
            {{ version }}
          </DownloadCard>
        </v-col>
      </v-row>
    </v-col>
  </v-row>
</template>

<script setup lang="ts">
import DownloadCard from '@/components/downloadCard/DownloadCard.vue'

import versions from './versions'
</script>
